[package]
name = "r55-output-bytecode"
version = "0.1.0"
edition = "2021"

[features]
default = []
with-bytecode = []

[dependencies]
alloy-core = { version = "0.8.20", default-features = false }

[[bin]]
name = "output"
path = "src/lib.rs"
